#!/bin/bash
clear
echo -e "$y  :::.       .:::.  .        :         :::.      ...    :::::::::::::::   ...          .::::::.   .,-::::: :::::::..   :::::::::::::. ::::::::::::$wh"
echo -e "$y  ;;`;;     ,;'``;. ;;,.    ;;;        ;;`;;     ;;     ;;;;;;;;;;;''''.;;;;;;;.      ;;;`    ` ,;;;'````' ;;;;``;;;;  ;;; `;;;```.;;;;;;;;;;;''''$wh"
echo -e "$y ,[[ '[[,   ''  ,[['[[[[, ,[[[[,      ,[[ '[[,  [['     [[[     [[    ,[[     \[[,    '[==/[[[[,[[[         [[[,/[[['  [[[  `]]nnn]]'      [[  $wh"   
echo -e "$yc$$$cc$$$c  .c$$P'  $$$$$$$$"$$$     c$$$cc$$$c $$      $$$     $$    $$$,     $$$      '''    $$$$         $$$$$$c    $$$   $$$""         $$     $wh"
echo -e "$y 888   888,d88 _,oo,888 Y88" 888o     888   888,88    .d888     88,   "888,_ _,88P     88b    dP`88bo,__,o, 888b "88bo,888   888o          88,    $wh"
echo -e "$y YMM   ""` MMMUP*"^^MMM  M'  "MMM     YMM   ""`  "YmmMMMM""     MMM     "YMMMMMP"       "YMmMY"   "YUMMMMMP"MMMM   "W" MMM   YMMMb         MMM  $wh"
echo -e "$y                MENU UTAMA $wh"
echo -e "$y-------------------------------------------------$wh"
echo -e "$yy 1$y.  Buat Akun Trojan GO $wh"
echo -e "$yy 2$y.  Hapus Akun Trojan GO$wh"
echo -e "$yy 3$y.  Perpanjang Akun Trojan GO$wh"
echo -e "$yy 4$y.  Buat Akun VMESS $wh"
echo -e "$yy 5$y.  Hapus Akun VMESS $wh"
echo -e "$yy 6$y.  Perpanjang VMESS$wh"
echo -e "$yy 7$y.  Restart Trojan GO$wh"
echo -e "$yy 8$y.  Cek Trojan$wh"
echo -e "$yy 9$y.  Cek VMESS$wh"
echo -e "$yy 10$y.  Reboot VPS$wh"
echo -e "$yy 11$y.  Ganti Domain$wh"
echo -e "$y-------------------------------------------------$wh"
read -p "Select From Options [ 1 - 6 ] : " menu
case $menu in
1)
clear
ak
;;
2)
clear
del
;;
3)
clear
renew
;;
4)
clar
addv2ray
;;
5)
clear
delv2ray
;;
6)
clear
renewv2ray
;;
7)
clear
restart
;;
8)
clear
cektrojan
;;
9)
clear
cekv2ray
;;
10)
clear
reboot
;;
11)
clear
addhost
;;
*)
clear
menu
;;
esac
